[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
log-db = False
syslog = False
log-level = info
admin_passwd = $pbkdf2-sha512$600000$h1AK4bxXCuE8B8BYi7FWig$1yJIT3Kt9oY4fAZYmseGJriZK7NYWU9BTbjg/pc333zxkIJT2EnC9cLSZ1CbsXXmRuVoBZv3HDNBdDVjr9nWlw

